all: papers-es.jpg whipalaNico.jpeg

papers-es.jpg:
	wget https://raw.githubusercontent.com/BayesPlurinacional/static/main/figuras/papers-es.jpg
	wget https://raw.githubusercontent.com/BayesPlurinacional/static/main/figuras/papers-en.jpg

whipalaNico.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/whipalaNico.jpeg

ariel-crop.jpg:
	convert ariel.jpg -crop 991x991+0+140 ariel-crop.jpg
